server:
  port: 8081

spring:
  data:
    redis:
      host: 192.168.100.80
      database: 0
      password: abc123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.100.80:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: abc123
    driver: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool

jackson:
  time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  default-flat-param-object: true

aliyun:
  sms:
    access-key-id: LTAI5tSbKYXS3LVnF1i5jj9g
    access-key-secret: yDdvAo27UvyNLr8ifxZWK6KTCJ6dpc
    endpoint: dysmsapi.aliyuncs.com
